//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saferide.Ressources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saferide.Ressources.AppTexts", typeof(AppTexts).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add incident.
        /// </summary>
        public static string AddIncident {
            get {
                return ResourceManager.GetString("AddIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address : .
        /// </summary>
        public static string AddressView {
            get {
                return ResourceManager.GetString("AddressView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the vocal recognition just press the listen button then say the texts that is displayed on the screen to click on that button..
        /// </summary>
        public static string AvailableCommands {
            get {
                return ResourceManager.GetString("AvailableCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both email and password needs to be completed.
        /// </summary>
        public static string BothFields {
            get {
                return ResourceManager.GetString("BothFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the unit system.
        /// </summary>
        public static string ChooseUnitSystem {
            get {
                return ResourceManager.GetString("ChooseUnitSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        public static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm?.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm that the incident was there?.
        /// </summary>
        public static string ConfirmText {
            get {
                return ResourceManager.GetString("ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected as : .
        /// </summary>
        public static string ConnectedAs {
            get {
                return ResourceManager.GetString("ConnectedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger.
        /// </summary>
        public static string Danger {
            get {
                return ResourceManager.GetString("Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U need to enable location first.
        /// </summary>
        public static string EnableLocation {
            get {
                return ResourceManager.GetString("EnableLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENE.
        /// </summary>
        public static string ENE {
            get {
                return ResourceManager.GetString("ENE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the description here.
        /// </summary>
        public static string EnterDescription {
            get {
                return ResourceManager.GetString("EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESE.
        /// </summary>
        public static string ESE {
            get {
                return ResourceManager.GetString("ESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the incident please..
        /// </summary>
        public static string GiveADescription {
            get {
                return ResourceManager.GetString("GiveADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which type of incident would you like to report?.
        /// </summary>
        public static string GiveANewIncident {
            get {
                return ResourceManager.GetString("GiveANewIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just say new incident to start reporting an incident.
        /// </summary>
        public static string GoToNewIncident {
            get {
                return ResourceManager.GetString("GoToNewIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        public static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading : .
        /// </summary>
        public static string HeadingView {
            get {
                return ResourceManager.GetString("HeadingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hole.
        /// </summary>
        public static string Hole {
            get {
                return ResourceManager.GetString("Hole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents.
        /// </summary>
        public static string Incidents {
            get {
                return ResourceManager.GetString("Incidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happened, check your internet connection.
        /// </summary>
        public static string InternetError {
            get {
                return ResourceManager.GetString("InternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/h.
        /// </summary>
        public static string Kilometersperhour {
            get {
                return ResourceManager.GetString("Kilometersperhour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude : .
        /// </summary>
        public static string LatitudeView {
            get {
                return ResourceManager.GetString("LatitudeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen.
        /// </summary>
        public static string Listen {
            get {
                return ResourceManager.GetString("Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new incident.
        /// </summary>
        public static string ListenNewIncident {
            get {
                return ResourceManager.GetString("ListenNewIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start riding.
        /// </summary>
        public static string ListenStartRiding {
            get {
                return ResourceManager.GetString("ListenStartRiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop riding.
        /// </summary>
        public static string ListenStopRiding {
            get {
                return ResourceManager.GetString("ListenStopRiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude : .
        /// </summary>
        public static string LongitudeView {
            get {
                return ResourceManager.GetString("LongitudeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.P.H.
        /// </summary>
        public static string MilesPerHour {
            get {
                return ResourceManager.GetString("MilesPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        public static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to danger.
        /// </summary>
        public static string NewDanger {
            get {
                return ResourceManager.GetString("NewDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hole.
        /// </summary>
        public static string NewHole {
            get {
                return ResourceManager.GetString("NewHole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obstacle.
        /// </summary>
        public static string NewObstacle {
            get {
                return ResourceManager.GetString("NewObstacle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sliding zone.
        /// </summary>
        public static string NewSlidingZone {
            get {
                return ResourceManager.GetString("NewSlidingZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NNE.
        /// </summary>
        public static string NNE {
            get {
                return ResourceManager.GetString("NNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NNW.
        /// </summary>
        public static string NNW {
            get {
                return ResourceManager.GetString("NNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string NoListen {
            get {
                return ResourceManager.GetString("NoListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.
        /// </summary>
        public static string NW {
            get {
                return ResourceManager.GetString("NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obstacle.
        /// </summary>
        public static string Obstacle {
            get {
                return ResourceManager.GetString("Obstacle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong :/ .
        /// </summary>
        public static string Oups {
            get {
                return ResourceManager.GetString("Oups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position : .
        /// </summary>
        public static string PositionView {
            get {
                return ResourceManager.GetString("PositionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please register on the website by clicking the button down bellow.
        /// </summary>
        public static string Registering {
            get {
                return ResourceManager.GetString("Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saferide.
        /// </summary>
        public static string Saferide {
            get {
                return ResourceManager.GetString("Saferide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You just sinagled and incident!.
        /// </summary>
        public static string SendAnIncident {
            get {
                return ResourceManager.GetString("SendAnIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an incident of the type {0} in {1} {2}. The description is {3}.
        /// </summary>
        public static string SignalIncident {
            get {
                return ResourceManager.GetString("SignalIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliding Zone.
        /// </summary>
        public static string SlidingZone {
            get {
                return ResourceManager.GetString("SlidingZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are some informations about the app.
        /// </summary>
        public static string SomeInfos {
            get {
                return ResourceManager.GetString("SomeInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak.
        /// </summary>
        public static string Speak {
            get {
                return ResourceManager.GetString("Speak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak now.
        /// </summary>
        public static string SpeakNow {
            get {
                return ResourceManager.GetString("SpeakNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed : .
        /// </summary>
        public static string SpeedView {
            get {
                return ResourceManager.GetString("SpeedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE.
        /// </summary>
        public static string SSE {
            get {
                return ResourceManager.GetString("SSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSW.
        /// </summary>
        public static string SSW {
            get {
                return ResourceManager.GetString("SSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start riding.
        /// </summary>
        public static string StartRiding {
            get {
                return ResourceManager.GetString("StartRiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U need to start riding first.
        /// </summary>
        public static string StartRidingFirst {
            get {
                return ResourceManager.GetString("StartRidingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop riding.
        /// </summary>
        public static string StopRiding {
            get {
                return ResourceManager.GetString("StopRiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        public static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait a second.
        /// </summary>
        public static string WaitASec {
            get {
                return ResourceManager.GetString("WaitASec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Saferide ! .
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you give the description?.
        /// </summary>
        public static string WhatOptionForIncident {
            get {
                return ResourceManager.GetString("WhatOptionForIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WNW.
        /// </summary>
        public static string WNW {
            get {
                return ResourceManager.GetString("WNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password or email is incorrect.
        /// </summary>
        public static string WrongLogins {
            get {
                return ResourceManager.GetString("WrongLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSW.
        /// </summary>
        public static string WSW {
            get {
                return ResourceManager.GetString("WSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string YesListen {
            get {
                return ResourceManager.GetString("YesListen", resourceCulture);
            }
        }
    }
}
